### ISSUE TITLE
Change paths to log files and pid file for Android deploy

### ISSUE THREAD

**Issue by dugdmitry** [dugdmitry/adhoc_routing#8]
Some default paths to log files, pidfile and UDS socket file do not exist in Android environment.
We need to change the default paths for android_deploy branch.
Default variables to be changed:

- Node_init.py:
line 39: `PIDFILE_PATH = "/var/run/routing_daemon.pid"`

- RoutingManager.py:
line 43: `self.server_address = "/tmp/uds_socket"`

- routing_logging.py:
line 28: `PATH_TO_LOGS = "/var/log/adhoc_routing/"`

**Comment by FastZombie** [comment]
Successfully modified all paths.
